const mock = {
  login: {
    list: { data: [], page: 1, size: 20 },
    data: {},
    user: {
      user_id: "93a54abd-2840-40a2-853e-93d0fc84148d",
      username: "samer.kayali@seidor.com.br",
      name: "Samer Kayali",
      mainTenant: "31060558-e334-4f1e-9681-2e01d3697e35",
      pk: "xkZUo2mvLU1unCMwNx67MaFoV8VL19qG9uhVPlOv",
      tenants: [
        {
          enabled: true,
          created_at: "2022-05-19T12:53:23.477Z",
          tenantId: "31060558-e334-4f1e-9681-2e01d3697e35",
          pk: "xkZUo2mvLU1unCMwNx67MaFoV8VL19qG9uhVPlOv",
          name: "Seidor Véritas",
          adminUser: "104e5b30-7269-4e42-98b8-968341b50605",
        },
      ],
    },
    errors: {},
    redirect: true,
    logged: true,
  },
  tenant: {
    selectedTenant: "xkZUo2mvLU1unCMwNx67MaFoV8VL19qG9uhVPlOv",
    selectedGroup: "",
    selectedCompany: "",
    selectedBranch: "",
    tenants: [
      {
        enabled: true,
        created_at: "2022-05-19T12:53:23.477Z",
        tenantId: "31060558-e334-4f1e-9681-2e01d3697e35",
        pk: "xkZUo2mvLU1unCMwNx67MaFoV8VL19qG9uhVPlOv",
        name: "Seidor Véritas",
        adminUser: "104e5b30-7269-4e42-98b8-968341b50605",
      },
    ],
    errors: {},
  },
  modules: {
    list: { data: [], page: 1, size: 20 },
    data: [
      {
        module_id: "f382ac45-7a30-4eb2-9c06-6f0e3f3fe67a",
        name: "Outbound",
        description: ".",
        display_icon: "file",
        route: "outbound",
        has_access: true,
        created_at: "2021-06-16T18:26:45.978Z",
        submodules: [
          {
            submodule_id: "9aa66b12-36f0-4ad3-90c1-b0e068e39112",
            name: "Documentos Fiscais",
            description: "",
            display_icon: "folder",
            complete_route: "outbound/document",
            route: "document",
            enabled: true,
            has_access: true,
            created_at: "2021-06-16T18:33:23.225Z",
            services: [
              {
                service_id: "656e4c85-87c7-4617-a4bb-11b23727ee87",
                service_name: "NFS-e",
                description: "Nota Fiscal de Serviços Eletrônica",
                display_icon: "list",
                complete_route: "outbound/document/nfse",
                route: "nfse",
                enabled: true,
                has_access: true,
                created_at: "2021-06-16T18:46:49.887Z",
              },
              {
                service_id: "8aedf36d-7c53-4841-ad67-49c6efc12821",
                service_name: "NF-e",
                description: "Nota Fiscal de Produto Eletrônica",
                display_icon: "shopping-cart",
                complete_route: "outbound/document/nfe",
                route: "nfe",
                enabled: true,
                has_access: true,
                created_at: "2021-06-16T18:45:16.687Z",
              },
              {
                service_id: "d1e449a0-0b68-4573-bfe8-4508e9473807",
                service_name: "NFC-e",
                description: "Nota Fiscal de Consumidor Final Eletrônica",
                display_icon: "user",
                complete_route: "outbound/document/nfce",
                route: "nfce",
                enabled: true,
                has_access: true,
                created_at: "2021-06-16T18:46:15.331Z",
              },
            ],
          },
          {
            submodule_id: "ed6ee6bf-3b8f-4da2-8c9a-9e271ae8715b",
            name: "Monitores",
            description: "*",
            display_icon: "monitor",
            complete_route: "outbound/monitors",
            route: "monitors",
            enabled: true,
            has_access: true,
            created_at: "2021-11-29T13:27:39.954Z",
            services: [
              {
                service_id: "54182c39-3370-4b6e-bbe2-f56b0e35965d",
                service_name: "Ambiente Nacional SEFAZ",
                description: "Status da disponibilidade de serviço",
                display_icon: "activity",
                complete_route: "outbound/monitors/sefaz",
                route: "sefaz",
                enabled: true,
                has_access: true,
                created_at: "2021-11-29T13:30:40.350Z",
              },
              {
                service_id: "12854ea9-34d6-4e41-a1e8-a4058da0ce92",
                service_name: "Ambiente Municipal",
                description: "Status da disponibilidade de serviço",
                display_icon: "map",
                complete_route: "outbound/monitors/municipal",
                route: "municipal",
                enabled: true,
                has_access: true,
                created_at: "2021-12-13T14:12:43.954Z",
              },
            ],
          },
        ],
      },
      {
        module_id: "af72d8b0-8c63-408f-8272-ce7d2b7f41cb",
        name: "Varejo",
        description: ".",
        display_icon: "shopping-cart",
        route: "retail",
        has_access: false,
        created_at: "2021-06-16T18:27:48.146Z",
        submodules: [
          {
            submodule_id: "d9c0c83b-75b0-42de-84e0-383fc35ccc10",
            name: "Configurações de Fechamento",
            description: "",
            display_icon: "tool",
            complete_route: "retail/closure-configurations",
            route: "closure-configurations",
            enabled: true,
            has_access: false,
            created_at: "2021-06-16T19:38:45.946Z",
            services: [
              {
                service_id: "58e58c4d-11e1-4dec-b9b8-0b21435e45d5",
                service_name: "Tipos de Ajustes",
                description:
                  "Identificar e classificar os diferentes tipos de lançamentos de movimento de numerário.",
                display_icon: "tool",
                complete_route:
                  "retail/closure-configurations/adjustments-types",
                route: "adjustments-types",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:41:03.081Z",
              },
              {
                service_id: "318899a5-34a5-40fe-8cf5-5d3903cfa480",
                service_name: "Tipo de Numerário",
                description:
                  "Identificar e classificar os diferentes tipos de lançamentos de movimento de numerário.",
                display_icon: "box",
                complete_route: "retail/closure-configurations/cash-type",
                route: "cash-type",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:41:46.219Z",
              },
            ],
          },
          {
            submodule_id: "0030507c-75d3-4e5c-8626-bd2338f64595",
            name: "Movimentos",
            description: "",
            display_icon: "chevrons-right",
            complete_route: "retail/movements",
            route: "movements",
            enabled: true,
            has_access: false,
            created_at: "2021-06-16T19:28:11.685Z",
            services: [
              {
                service_id: "77c0ca95-1dd4-43b9-bcf9-d86e896093d6",
                service_name: "Sangria",
                description:
                  "Lançamento de movimento de saída. É responsável pelo controle e direcionamento do valor de retirada proveniente das vendas de lojas.",
                display_icon: "external-link",
                complete_route: "retail/movements/sangria",
                route: "sangria",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:30:57.981Z",
              },
              {
                service_id: "223c27ef-f692-4245-a431-97ae12555a2b",
                service_name: "Movimento de Numerário",
                description:
                  "Lançamento de Valor Monetário com o objetivo de identificar o destino dado ao dinheiro, após sua saída do PDV da filial.",
                display_icon: "box",
                complete_route: "retail/movements/numerary",
                route: "numerary",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:29:33.218Z",
              },
              {
                service_id: "54ee7f4b-003d-4200-8d68-014c805c9db3",
                service_name: "Troca de Meio de Pagamento",
                description:
                  "Processo que permite efetuar a troca do meio de pagamento de uma movimentação financeira.",
                display_icon: "copy",
                complete_route: "retail/movements/finisher-exchange",
                route: "finisher-exchange",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:31:41.033Z",
              },
              {
                service_id: "aba742bc-e0a0-4dd3-8530-d701af607c74",
                service_name: "Monitor de Integração",
                description:
                  "Gerenciador de status das Movimentações Integradas no Retail Web.",
                display_icon: "monitor",
                complete_route: "retail/movements/integration-monitor",
                route: "integration-monitor",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:28:59.036Z",
              },
              {
                service_id: "b175741c-6212-4fca-b34e-ae3098f14d3a",
                service_name: "Fechamento de Caixa",
                description:
                  "Gerenciador do processo de acompanhamento do movimento de venda. Comparar os Valores de Venda (entrada) versus as Movimentações de Totalizadores (Saídas).",
                display_icon: "dollar-sign",
                complete_route: "retail/movements/cash-closure",
                route: "cash-closure",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:30:19.594Z",
              },
            ],
          },
          {
            submodule_id: "3cdc3482-e793-4abf-8027-948314b97592",
            name: "Configurações Financeiras",
            description: "",
            display_icon: "dollar-sign",
            complete_route: "retail/financial-configurations",
            route: "financial-configurations",
            enabled: true,
            has_access: false,
            created_at: "2021-06-16T19:37:08.576Z",
            services: [
              {
                service_id: "6bc1271c-a149-40d5-aa2a-d0860d5cbcc2",
                service_name: "Meio de Pagamento",
                description:
                  "A forma como é identificado no pagamento da movimentação. São os métodos utilizados para o fechamento da venda.",
                display_icon: "credit-card",
                complete_route:
                  "retail/financial-configurations/payment-method",
                route: "payment-method",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:38:27.249Z",
              },
              {
                service_id: "3e98de80-8381-47d2-b0db-a7cff2e24569",
                service_name: "Condições de Pagamento",
                description:
                  "Identifica qual o prazo de pagamento será associado ao movimento financeiro.",
                display_icon: "credit-card",
                complete_route:
                  "retail/financial-configurations/payment-condition",
                route: "payment-condition",
                enabled: true,
                has_access: false,
                created_at: "2021-06-17T12:30:05.763Z",
              },
              {
                service_id: "0be06e7b-188e-45b2-8c4a-6f3c7b59254a",
                service_name: "Bandeiras",
                description:
                  "Gerenciamento de cartões e bandeiras associadas, para identificar os cartões utilizados nas compras.",
                display_icon: "flag",
                complete_route: "retail/financial-configurations/flags",
                route: "flags",
                enabled: true,
                has_access: false,
                created_at: "2021-07-21T17:43:48.880Z",
              },
              {
                service_id: "797fb711-62ff-4608-a3ed-48400990c7d9",
                service_name: "Administradora",
                description:
                  "Gerencie as administradoras de cartão para identificá-las na integração das vendas.",
                display_icon: "bookmark",
                complete_route:
                  "retail/financial-configurations/card-administrator",
                route: "card-administrator",
                enabled: true,
                has_access: false,
                created_at: "2021-07-21T19:46:33.981Z",
              },
            ],
          },
          {
            submodule_id: "f9aca556-3ccd-4c0f-825d-576abcc436ba",
            name: "Configurações de Filial",
            description: "",
            display_icon: "home",
            complete_route: "retail/branch-config",
            route: "branch-config",
            enabled: true,
            has_access: false,
            created_at: "2021-06-16T19:32:08.934Z",
            services: [
              {
                service_id: "e65c1999-02ff-4b8b-814b-caca18e0a463",
                service_name: "Clusters - Mix",
                description:
                  "Conjunto de lojas agrupadas para definição do mix de produtos.",
                display_icon: "package",
                complete_route: "retail/branch-config/clusters-mix",
                route: "clusters-mix",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:33:22.809Z",
              },
              {
                service_id: "5eea6743-aa96-4915-9288-92427b3efe0d",
                service_name: "Cluster - Imposto",
                description:
                  "Agrupamento de lojas que possibilita a análise das vendas por agrupamento.",
                display_icon: "align-center",
                complete_route: "retail/branch-config/cluster-tax",
                route: "cluster-tax",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:32:54.145Z",
              },
              {
                service_id: "2953c260-de4f-45fd-ac79-cf9c2872f172",
                service_name: "Canal de Venda",
                description:
                  "Identifica qual foi o canal/meio utilizado pelo sistema legado para a venda ao consumidor.",
                display_icon: "shopping-cart",
                complete_route: "retail/branch-config/sales-channel",
                route: "sales-channel",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:40:27.847Z",
              },
              {
                service_id: "d8084aeb-4142-4e6b-a185-3b61ac4c916d",
                service_name: "Ponto de Venda",
                description: "Cadastro do equipamento (PDV) do sistema legado.",
                display_icon: "home",
                complete_route: "retail/branch-config/points-of-sale",
                route: "points-of-sale",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:27:02.665Z",
              },
              {
                service_id: "75e300d8-7c00-4b15-86e6-5fb756b6620e",
                service_name: "Operador",
                description:
                  "Cadastro da pessoa responsável pelo processo de venda no Sistema Legado.",
                display_icon: "user",
                complete_route: "retail/branch-config/operator",
                route: "operator",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:27:36.524Z",
              },
              {
                service_id: "06ebd15b-c25d-4433-b5e2-57173454935d",
                service_name: "Classificação de Estoque",
                description:
                  "Identifica e classifica as nomenclaturas de impostos.",
                display_icon: "pocket",
                complete_route: "retail/branch-config/stock-classification",
                route: "stock-classification",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:33:58.166Z",
              },
            ],
          },
          {
            submodule_id: "2f3b7d35-9eaa-46bd-be62-90465d68f602",
            name: "Configurações Gerais",
            description: "",
            display_icon: "settings",
            complete_route: "retail/configurations",
            route: "configurations",
            enabled: true,
            has_access: false,
            created_at: "2021-06-16T19:34:13.306Z",
            services: [
              {
                service_id: "56d5dd63-8da3-4349-a4bf-a2b2db7e491f",
                service_name: "Sistema Legado",
                description:
                  "Sistema externo responsável pelo envio dos movimentos fiscais, não fiscais e financeiros.",
                display_icon: "hard-drive",
                complete_route: "retail/configurations/legacy-system",
                route: "legacy-system",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:39:36.339Z",
              },
              {
                service_id: "66af9bc8-c4f4-4539-9012-e167c5bba4c3",
                service_name: "Valores Adicionais",
                description:
                  "Identificar e classificar os diferentes tipos de valores adicionais que podem existir nos movimentos de venda.",
                display_icon: "plus-circle",
                complete_route: "retail/configurations/additional-value",
                route: "additional-value",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:37:52.263Z",
              },
              {
                service_id: "3219594d-0ec2-4b89-a197-554f4034141b",
                service_name: "Condições de Valores",
                description: "Gerenciador das Condições de Valores.",
                display_icon: "alert-octagon",
                complete_route: "retail/configurations/price-condition",
                route: "price-condition",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:36:48.305Z",
              },
            ],
          },
          {
            submodule_id: "65689fa5-9e54-4251-8d6f-238cc507707a",
            name: "Relatórios",
            description: "Relatórios para controle do varejo",
            display_icon: "trending-up",
            complete_route: "retail/reports",
            route: "reports",
            enabled: true,
            has_access: false,
            created_at: "2021-08-27T15:32:29.716Z",
            services: [
              {
                service_id: "82e4c043-fe33-42ff-83a9-11ad0cdd9328",
                service_name: "Vendas por bandeira",
                description: "Detalhes das vendas por bandeira.",
                display_icon: "credit-card",
                complete_route: "retail/reports/sales-flag-report",
                route: "sales-flag-report",
                enabled: true,
                has_access: false,
                created_at: "2021-08-30T10:37:19.523Z",
              },
              {
                service_id: "e6ef9efa-a61e-4a0f-8cbb-febd7df13b39",
                service_name: "Tesouraria",
                description:
                  "Detalhes de valores e status do fechamento de caixa.",
                display_icon: "dollar-sign",
                complete_route: "retail/reports/treasury-report",
                route: "treasury-report",
                enabled: true,
                has_access: false,
                created_at: "2021-08-30T10:39:58.849Z",
              },
              {
                service_id: "5210de53-6523-435e-be62-b2f4c430a864",
                service_name: "Vendas",
                description: "Detalhes de vendas por meio de pagamento",
                display_icon: "pocket",
                complete_route: "retail/reports/sales-report",
                route: "sales-report",
                enabled: true,
                has_access: false,
                created_at: "2021-08-30T10:35:16.012Z",
              },
            ],
          },
          {
            submodule_id: "0da3fad9-e74d-4c14-ab92-0fba13cfcc89",
            name: "Gestão de Mercadorias",
            description: "",
            display_icon: "clipboard",
            complete_route: "retail/merchandise-management",
            route: "merchandise-management",
            enabled: true,
            has_access: false,
            created_at: "2021-06-16T19:26:21.530Z",
            services: [
              {
                service_id: "237c7c35-8ce4-40ee-b9d2-ebc4be812993",
                service_name: "Características",
                description: "Gerenciador de Características.",
                display_icon: "life-buoy",
                complete_route: "retail/merchandise-management/characteristics",
                route: "characteristics",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:35:15.075Z",
              },
              {
                service_id: "6cb718f2-24e5-431e-9b44-bd6931a2c554",
                service_name: "Grupo de Características",
                description: "Gerenciador de Grupo de Características.",
                display_icon: "grid",
                complete_route:
                  "retail/merchandise-management/characteristics-group",
                route: "characteristics-group",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:35:41.668Z",
              },
              {
                service_id: "71c9c93e-db2d-4ca1-be26-a70972fe0eca",
                service_name: "Comprador",
                description: "Identifica os compradores de produtos.",
                display_icon: "shopping-bag",
                complete_route: "retail/merchandise-management/buyer",
                route: "buyer",
                enabled: true,
                has_access: false,
                created_at: "2021-09-29T13:55:41.128Z",
              },
              {
                service_id: "f71586fb-f60c-4783-b4f1-ddd598f5da93",
                service_name: "Marcas",
                description: "Cadastro de marcas dos produtos.",
                display_icon: "tag",
                complete_route: "retail/merchandise-management/brands",
                route: "brands",
                enabled: true,
                has_access: false,
                created_at: "2021-09-27T14:16:00.611Z",
              },
              {
                service_id: "efe47f11-ceac-4d62-bfcd-d310169bcd6a",
                service_name: "Lista de preço",
                description:
                  "Lista customizada que permite a gestão de preços dos produtos ",
                display_icon: "dollar-sign",
                complete_route: "retail/merchandise-management/price-list",
                route: "price-list",
                enabled: true,
                has_access: false,
                created_at: "2021-10-18T12:53:37.817Z",
              },
              {
                service_id: "47124903-0231-4b3c-8924-93579a749499",
                service_name: "Produtos",
                description:
                  "Gerenciamento de famílias, produtos e suas variantes.",
                display_icon: "shopping-bag",
                complete_route: "retail/merchandise-management/products",
                route: "products",
                enabled: true,
                has_access: false,
                created_at: "2021-10-18T13:36:37.751Z",
              },
              {
                service_id: "cdec259f-65f4-4866-86c0-9c3a5de7c513",
                service_name: "Árvore Mercadológica",
                description: "Gerenciador da setorização dos materiais.",
                display_icon: "map",
                complete_route: "retail/merchandise-management/market-tree",
                route: "market-tree",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:36:11.055Z",
              },
            ],
          },
        ],
      },
      {
        module_id: "251a42da-00e3-4509-b509-01fbe221ac8e",
        name: "4Tax - Brasil",
        description: ".",
        display_icon: "dollar-sign",
        route: "/tax",
        has_access: true,
        created_at: "2021-06-16T18:28:25.900Z",
        submodules: [
          {
            submodule_id: "eb95c0a3-9dd6-4fb0-a775-f78c0f1d7f67",
            name: "ECD",
            description: "",
            display_icon: "monitor",
            complete_route: "/tax/ecd",
            route: "ecd",
            enabled: true,
            has_access: false,
            created_at: "2021-06-16T19:03:25.317Z",
            services: [
              {
                service_id: "9244d9f8-0c57-4e67-9a4f-2e5ea022f5ff",
                service_name: "Geração do Arquivo",
                description: "Arquivos gerados para apresentação ao Fisco.",
                display_icon: "file",
                complete_route: "/tax/ecd/file",
                route: "file",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:05:06.737Z",
              },
              {
                service_id: "6daa4c18-59bb-4023-8361-f305a7532fb8",
                service_name: "Lançamentos Contábeis",
                description:
                  "O conjunto de contas, previamente estabelecido, que norteia os trabalhos contábeis de registros, fatos e atos inerentes à entidade, além de servir de parâmetro para a elaboração das demonstrações contábeis.",
                display_icon: "book",
                complete_route: "/tax/ecd/accountingDocument",
                route: "accountingDocument",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:08:07.473Z",
              },
              {
                service_id: "f7a016b6-8cd3-431d-a5db-dde77a2a0dc7",
                service_name: "Transações Contábeis",
                description:
                  "Documentos que descrevem todos os dados contábeis e financeiros de uma organização em um determinado período.",
                display_icon: "shuffle",
                complete_route: "/tax/ecd/transacciones-contables",
                route: "transacciones-contables",
                enabled: true,
                has_access: false,
                created_at: "2021-10-06T11:14:33.313Z",
              },
              {
                service_id: "05625d44-c43c-4194-9ca7-c2665bdd4a83",
                service_name: "Vincular Fatos Contábeis",
                description:
                  "DLPA - Demonstração de Lucros ou Prejuízos Acumulados / DMPL - Demonstração de Mutações do Patrimônio Líquido",
                display_icon: "list",
                complete_route: "/tax/ecd/dlpaDmpl",
                route: "dlpaDmpl",
                enabled: true,
                has_access: false,
                created_at: "2022-11-11T17:38:24.054Z",
              },
            ],
          },
          {
            submodule_id: "8740a1da-1add-4d3d-a815-7a8673bff61a",
            name: "EFD Contribuições",
            description: null,
            display_icon: null,
            complete_route: "/tax/efdcontributions",
            route: "efdcontributions",
            enabled: true,
            has_access: false,
            created_at: "2021-08-04T15:11:44.549Z",
            services: [
              {
                service_id: "c63d028a-ca81-47b5-97a8-3d4fc27dfa65",
                service_name: "Registro - Bloco M",
                description:
                  "Registro da Contribuição e Crédito do PIS/Pasep e da Cofins.",
                display_icon: "list",
                complete_route: "/tax/efdcontributions/verificationMBlock",
                route: "verificationMBlock",
                enabled: true,
                has_access: false,
                created_at: "2021-08-23T11:55:02.542Z",
              },
              {
                service_id: "caac4a32-79dc-44c9-ae3b-a659a21b6b1b",
                service_name: "Registros",
                description: "Parâmetros dos Registros.",
                display_icon: "file-text",
                complete_route: "/tax/efdcontributions/records",
                route: "records",
                enabled: true,
                has_access: false,
                created_at: "2021-08-04T15:13:32.732Z",
              },
              {
                service_id: "9244d9f8-0c57-4e67-9a4f-2e5ea022f5ff",
                service_name: "Geração do Arquivo",
                description: "Arquivos gerados para apresentação ao Fisco.",
                display_icon: "file",
                complete_route: "/tax/efdcontributions/file",
                route: "file",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:05:06.737Z",
              },
              {
                service_id: "57c08f7a-061b-483d-8683-fc20e453c0a0",
                service_name: "Apuração PIS e COFINS",
                description: "Apuração do PIS e COFINS.",
                display_icon: "file-text",
                complete_route: "/tax/efdcontributions/verifications",
                route: "verifications",
                enabled: true,
                has_access: false,
                created_at: "2022-06-29T14:09:39.747Z",
              },
            ],
          },
          {
            submodule_id: "ea5c905a-08d5-4593-9130-c9117181a3de",
            name: "EFD ICMS IPI",
            description: "",
            display_icon: "percent",
            complete_route: "/tax/icmsipi",
            route: "icmsipi",
            enabled: true,
            has_access: false,
            created_at: "2021-06-16T19:19:47.776Z",
            services: [
              {
                service_id: "7a3c6391-b0d8-4f0b-aa21-a37e777afde0",
                service_name: "Apuração ICMS/IPI",
                description: "Apuração do ICMS, IPI, ICMS ST e DIFAL / FCP.",
                display_icon: "file-text",
                complete_route: "/tax/icmsipi/verification",
                route: "verification",
                enabled: true,
                has_access: false,
                created_at: "2022-06-29T14:12:23.167Z",
              },
              {
                service_id: "5574c59a-8bc7-432b-9a80-fb103dca928e",
                service_name: "Outras Informações",
                description:
                  "Preenchimento das informações referente ao Registro 1010.",
                display_icon: "file-text",
                complete_route: "/tax/icmsipi/others",
                route: "others",
                enabled: true,
                has_access: false,
                created_at: "2021-07-19T15:00:54.164Z",
              },
              {
                service_id: "1e09a781-f113-48d8-9405-ffac93b710ec",
                service_name: "Períodos",
                description: "Refere-se ao mês de apuração do imposto.",
                display_icon: "clock",
                complete_route: "/tax/icmsipi/periods",
                route: "periods",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:21:43.969Z",
              },
              {
                service_id: "9244d9f8-0c57-4e67-9a4f-2e5ea022f5ff",
                service_name: "Geração do Arquivo",
                description: "Arquivos gerados para apresentação ao Fisco.",
                display_icon: "file",
                complete_route: "/tax/icmsipi/file",
                route: "file",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:05:06.737Z",
              },
              {
                service_id: "073d7631-6248-4a8c-ba66-0d1823d7c3bb",
                service_name: "Registros Bloco E",
                description:
                  "Registros pertinentes ao Bloco E do SPED ICMS IPI.",
                display_icon: "book-open",
                complete_route: "/tax/icmsipi/eblock",
                route: "eblock",
                enabled: true,
                has_access: false,
                created_at: "2021-12-07T12:53:30.354Z",
              },
              {
                service_id: "60f46c18-cb26-492c-9285-ddbd73477a08",
                service_name: "Registros Bloco H",
                description:
                  "Registros pertinentes ao Bloco H do SPED ICMS IPI.",
                display_icon: "book-open",
                complete_route: "/tax/icmsipi/hblock",
                route: "hblock",
                enabled: true,
                has_access: false,
                created_at: "2022-11-01T11:50:03.567Z",
              },
            ],
          },
          {
            submodule_id: "37746180-3acd-4ec4-853a-a6210f3547c9",
            name: "ECF",
            description: ".",
            display_icon: "book-open",
            complete_route: "/tax/ecf",
            route: "ecf",
            enabled: true,
            has_access: false,
            created_at: "2021-06-16T19:08:47.440Z",
            services: [
              {
                service_id: "6daa4c18-59bb-4023-8361-f305a7532fb8",
                service_name: "Lançamentos Contábeis",
                description:
                  "O conjunto de contas, previamente estabelecido, que norteia os trabalhos contábeis de registros, fatos e atos inerentes à entidade, além de servir de parâmetro para a elaboração das demonstrações contábeis.",
                display_icon: "book",
                complete_route: "/tax/ecf/accountingDocument",
                route: "accountingDocument",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:08:07.473Z",
              },
              {
                service_id: "feadc5a5-6bc9-4172-81ab-f025639d95f4",
                service_name: "Relatórios Contábeis",
                description:
                  "Documentos que descrevem todos os dados contábeis e financeiros de uma organização em um determinado período.",
                display_icon: "archive",
                complete_route: "/tax/ecf/accountingReports",
                route: "accountingReports",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:17:46.529Z",
              },
              {
                service_id: "46f3faae-25a3-485a-b18e-8955ac1afb82",
                service_name: "Plano de Contas Referenciais",
                description:
                  "O conjunto de contas, previamente estabelecido, que norteia os trabalhos contábeis de registros, fatos e atos inerentes à entidade, além de servir de parâmetro para a elaboração das demonstrações contábeis.",
                display_icon: "columns",
                complete_route: "/tax/ecf/chartReferencialAccounts",
                route: "chartReferencialAccounts",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:10:23.786Z",
              },
              {
                service_id: "f442873b-0fdc-4302-9c61-365b1067dc09",
                service_name: "Cadastros Auxiliares",
                description: "Outras Informações Gerais para apuração.",
                display_icon: "file",
                complete_route: "/tax/ecf/auxiliaryRegistrations",
                route: "auxiliaryRegistrations",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T18:52:18.435Z",
              },
            ],
          },
          {
            submodule_id: "39263154-a293-4b04-bd4f-0ca8b43feade",
            name: "Configurações Gerais",
            description: null,
            display_icon: "settings",
            complete_route: "/tax/generalSettings",
            route: "generalSettings",
            enabled: true,
            has_access: true,
            created_at: "2022-03-10T20:15:27.273Z",
            services: [
              {
                service_id: "1af283c8-5ec5-4c1f-b9a3-1377faef4ddd",
                service_name: "Centro de Custo",
                description:
                  "Unidades dentro de uma organização aos quais se alocam despesas e receitas, geralmente são projetos ou departamentos de uma empresa.",
                display_icon: "package",
                complete_route: "/tax/generalSettings/costCenters",
                route: "costCenters",
                enabled: true,
                has_access: true,
                created_at: "2021-06-16T19:07:27.900Z",
              },
              {
                service_id: "0076323b-d068-412a-b4fa-388cf3874e80",
                service_name: "Planos de Contas",
                description:
                  "A forma como a Contabilidade registra os fatos que afetam (ou que possam vir a afetar) o patrimônio da empresa.",
                display_icon: "book-open",
                complete_route: "/tax/generalSettings/chartAccounts",
                route: "chartAccounts",
                enabled: true,
                has_access: true,
                created_at: "2021-06-16T19:06:47.762Z",
              },
              {
                service_id: "a538b6d6-fb5e-46c8-b925-11492b777319",
                service_name: "Perfil Fiscal",
                description:
                  "Conjunto de propriedades gerais ou específicas ao módulo.",
                display_icon: "list",
                complete_route: "/tax/generalSettings/taxProfileList",
                route: "taxProfileList",
                enabled: true,
                has_access: true,
                created_at: "2021-06-16T18:50:18.318Z",
              },
              {
                service_id: "4613e4a1-b392-4b34-ab1f-6af13dcccaae",
                service_name: "Contas Contábeis",
                description:
                  "Denominações técnicas utilizadas para representar os elementos de mesma natureza sejam patrimoniais ou de resultado.",
                display_icon: "clipboard",
                complete_route: "/tax/generalSettings/financialAccounts",
                route: "financialAccounts",
                enabled: true,
                has_access: true,
                created_at: "2021-06-16T19:05:47.921Z",
              },
            ],
          },
          {
            submodule_id: "503c532f-399e-4362-8aad-1683a406cee2",
            name: "REINF",
            description: "",
            display_icon: "grid",
            complete_route: "/tax/reinf",
            route: "reinf",
            enabled: true,
            has_access: false,
            created_at: "2021-06-16T18:49:23.167Z",
            services: [
              {
                service_id: "a62a9be3-5df9-45fc-88ba-1553fdc775a8",
                service_name: "Eventos Não Periódicos",
                description:
                  "Eventos da REINF que não possuem data pré-fixada pra ocorrerem.",
                display_icon: "calendar",
                complete_route: "/tax/reinf/nonPeriodicEvents",
                route: "nonPeriodicEvents",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T18:50:58.165Z",
              },
              {
                service_id: "64ece514-2daf-48ba-9b7c-84ffc4e5040f",
                service_name: "Eventos Periódicos",
                description: "Eventos da REINF com datas fixas para ocorrerem.",
                display_icon: "clock",
                complete_route: "/tax/reinf/periodicEvents",
                route: "periodicEvents",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T18:51:40.863Z",
              },
              {
                service_id: "f442873b-0fdc-4302-9c61-365b1067dc09",
                service_name: "Cadastros Auxiliares",
                description: "Outras Informações Gerais para apuração.",
                display_icon: "file",
                complete_route: "/tax/reinf/auxiliaryRegistrations",
                route: "auxiliaryRegistrations",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T18:52:18.435Z",
              },
            ],
          },
          {
            submodule_id: "cb760694-1ddb-4f60-a46f-a20b8e7f2c3e",
            name: "DIRF",
            description: "",
            display_icon: "file-text",
            complete_route: "/tax/dirf",
            route: "dirf",
            enabled: true,
            has_access: false,
            created_at: "2021-06-16T18:52:38.963Z",
            services: [
              {
                service_id: "4b63e367-5033-420f-94a0-6c7cd0d34f55",
                service_name: "Gestão de Arquivos",
                description:
                  "Conjunto dos arquivos gerados para apresentação ao Fisco.",
                display_icon: "calendar",
                complete_route: "/tax/dirf/filesManagement",
                route: "filesManagement",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:02:15.757Z",
              },
              {
                service_id: "2bbc156c-d50d-422b-bf28-1a26062e584b",
                service_name: "Rendimentos Tributáveis",
                description: "São Rendimentos aos quais os impostos incidem.",
                display_icon: "file",
                complete_route: "/tax/dirf/taxableIncome",
                route: "taxableIncome",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:03:09.457Z",
              },
            ],
          },
          {
            submodule_id: "c5c1561e-6199-4f08-9b13-674ad85960bb",
            name: "Gerenciamento de Arquivos",
            description: "",
            display_icon: "archive",
            complete_route: "/tax/others",
            route: "others",
            enabled: true,
            has_access: false,
            created_at: "2021-06-16T19:23:59.665Z",
            services: [
              {
                service_id: "3bd7af85-f6b2-4aec-8794-b03b7e1bddf9",
                service_name: "Monitor",
                description:
                  "Visualização dos status das gerações dos arquivos fiscais.",
                display_icon: "monitor",
                complete_route: "/tax/others/monitor",
                route: "monitor",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:24:45.350Z",
              },
            ],
          },
          {
            submodule_id: "088ad306-f701-454e-be99-87ccaae665b2",
            name: "GIA-SP",
            description: null,
            display_icon: "file-text",
            complete_route: "/tax/giasp",
            route: "giasp",
            enabled: true,
            has_access: false,
            created_at: "2022-11-23T17:41:03.207Z",
            services: [
              {
                service_id: "9244d9f8-0c57-4e67-9a4f-2e5ea022f5ff",
                service_name: "Geração do Arquivo",
                description: "Arquivos gerados para apresentação ao Fisco.",
                display_icon: "file",
                complete_route: "/tax/giasp/file",
                route: "file",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:05:06.737Z",
              },
            ],
          },
          {
            submodule_id: "665e84e8-93c0-46a2-9897-cab7fa0ad015",
            name: "DCTF Mensal",
            description: null,
            display_icon: "file-text",
            complete_route: "/tax/dctf",
            route: "dctf",
            enabled: true,
            has_access: false,
            created_at: "2021-12-23T16:26:01.379Z",
            services: [
              {
                service_id: "9244d9f8-0c57-4e67-9a4f-2e5ea022f5ff",
                service_name: "Geração do Arquivo",
                description: "Arquivos gerados para apresentação ao Fisco.",
                display_icon: "file",
                complete_route: "/tax/dctf/file",
                route: "file",
                enabled: true,
                has_access: false,
                created_at: "2021-06-16T19:05:06.737Z",
              },
              {
                service_id: "2331b12a-6894-4d85-a26e-2527c8fcbc39",
                service_name: "Débitos Apurados e Créditos Vinculados",
                description:
                  "Apresentação dos Impostos devidos ou creditados no período.",
                display_icon: "file-text",
                complete_route: "/tax/dctf/rblock",
                route: "rblock",
                enabled: true,
                has_access: false,
                created_at: "2022-01-14T12:51:42.198Z",
              },
            ],
          },
          {
            submodule_id: "962cb7dc-a9fa-4935-b915-78c0b57547c8",
            name: "Outros Documentos",
            description: null,
            display_icon: null,
            complete_route: "/tax/othersDocuments",
            route: "othersDocuments",
            enabled: true,
            has_access: false,
            created_at: "2021-08-23T11:46:19.668Z",
            services: [
              {
                service_id: "9fd01d4a-82bf-4406-8d3f-8f5fb6bca5d5",
                service_name: "Outros Documentos",
                description:
                  "Registro dos demais documentos de entrada e saída.",
                display_icon: "file-text",
                complete_route: "/tax/othersDocuments/othersDocuments",
                route: "othersDocuments",
                enabled: true,
                has_access: false,
                created_at: "2021-08-23T11:47:27.869Z",
              },
            ],
          },
          {
            submodule_id: "a647ba3c-13f0-48a7-88e6-a214a89f7f08",
            name: "Relatórios",
            description: null,
            display_icon: "pie-chart",
            complete_route: "/tax/reports",
            route: "reports",
            enabled: true,
            has_access: true,
            created_at: "2022-05-09T14:29:24.581Z",
            services: [
              {
                service_id: "1c53399a-bca4-443c-8c22-c1eedb041c15",
                service_name: "Movimento Fiscal",
                description:
                  "Relatório fiscal de documentos de entrada e saída, para auxiliar a conferência da escrituração e apuração dos impostos.",
                display_icon: "refresh-cw",
                complete_route: "/tax/reports/taxmovement",
                route: "taxmovement",
                enabled: true,
                has_access: true,
                created_at: "2022-05-09T14:31:33.650Z",
              },
              {
                service_id: "a056f62f-9ab7-4ecf-82f3-60bc7ccd63f6",
                service_name: "Retidos",
                description: "Relatório Fiscal dos impostos retidos na fonte.",
                display_icon: "file",
                complete_route: "/tax/reports/retainedreports",
                route: "retainedreports",
                enabled: true,
                has_access: true,
                created_at: "2022-05-16T14:24:56.943Z",
              },
            ],
          },
          {
            submodule_id: "6786339e-cf2b-4ba7-94f4-a34f7f879bfc",
            name: "Obrigações Municipais",
            description: ".",
            display_icon: "file-text",
            complete_route: "/tax/municipalObligations",
            route: "municipalObligations",
            enabled: true,
            has_access: true,
            created_at: "2022-02-03T17:41:11.810Z",
            services: [
              {
                service_id: "6106dbc5-fad8-42fe-90cb-f9fabf5adf80",
                service_name: "Geração de Arquivos Municipais",
                description:
                  "Arquivos gerados para apresentação ao fisco municipal.",
                display_icon: "file-text",
                complete_route: "/tax/municipalObligations/fileGeneration",
                route: "fileGeneration",
                enabled: true,
                has_access: true,
                created_at: "2022-02-03T17:48:22.522Z",
              },
            ],
          },
        ],
      },
      {
        module_id: "ad3958e3-7bbd-445b-89e8-f3a46984913c",
        name: "Portal de Fornecedores",
        description: ".",
        display_icon: "truck",
        route: "suppliersPortal",
        has_access: true,
        created_at: "2021-06-16T18:29:25.486Z",
        submodules: [
          {
            submodule_id: "e3da4c3b-a4a0-4a93-938b-a5c1365b2b86",
            name: "Fornecedores",
            description: "",
            display_icon: "truck",
            complete_route: "suppliersPortal/suppliers",
            route: "suppliers",
            enabled: true,
            has_access: true,
            created_at: "2021-06-17T13:29:15.449Z",
            services: [
              {
                service_id: "578f7b53-a050-422b-a5b2-a948dbe936b1",
                service_name: "Configurações",
                description: "Defina as regras para upload de documentos.",
                display_icon: "settings",
                complete_route: "suppliersPortal/suppliers/settings",
                route: "settings",
                enabled: true,
                has_access: true,
                created_at: "2021-10-20T12:08:50.143Z",
              },
              {
                service_id: "c09f693e-f600-48d4-a9c4-50d1f43723ba",
                service_name: "Lista de Fornecedores",
                description:
                  "Visualize os fornecedores e reenvie os e-mails de cadastro.",
                display_icon: "users",
                complete_route: "suppliersPortal/suppliers/supplierList",
                route: "supplierList",
                enabled: true,
                has_access: true,
                created_at: "2021-09-09T19:14:46.869Z",
              },
              {
                service_id: "35a9e398-daa4-498b-9728-29c5c394b8e2",
                service_name: "Pedidos de Compra",
                description:
                  "Consulte a lista dos pedidos de compra dos seus clientes.",
                display_icon: "clipboard",
                complete_route: "suppliersPortal/suppliers/purchaseOrders",
                route: "purchaseOrders",
                enabled: true,
                has_access: true,
                created_at: "2022-06-29T13:13:47.659Z",
              },
              {
                service_id: "d6ca7a42-4518-4211-b787-cc5626e8e7a6",
                service_name: "Lista de Documentos",
                description:
                  "Lista completa de documentos e notas do nosso parceiro.",
                display_icon: "file",
                complete_route: "suppliersPortal/suppliers/documentsList",
                route: "documentsList",
                enabled: true,
                has_access: true,
                created_at: "2021-06-17T13:28:59.078Z",
              },
            ],
          },
        ],
      },
      {
        module_id: "5fa61c9d-41b0-47b3-a77d-e4ffc445eaf8",
        name: "Recursos Humanos",
        description: ".",
        display_icon: "users",
        route: "humanResources",
        has_access: true,
        created_at: "2021-10-08T17:42:13.437Z",
        submodules: [
          {
            submodule_id: "7ae8b336-2b5f-4042-b24f-d9de2664033e",
            name: "Gestão",
            description: null,
            display_icon: "archive",
            complete_route: "humanResources/management",
            route: "management",
            enabled: true,
            has_access: true,
            created_at: "2021-10-08T17:49:40.979Z",
            services: [
              {
                service_id: "40d9d34e-dfc2-46fd-99b5-01a5c68df5af",
                service_name: "Contratos",
                description:
                  "Veja a lista completa dos contratos cadastrados, crie, edite e inative de acordo com a necessidade do seu negócio.",
                display_icon: "trello",
                complete_route: "humanResources/management/contracts",
                route: "contracts",
                enabled: true,
                has_access: true,
                created_at: "2021-12-09T18:46:35.699Z",
              },
              {
                service_id: "a7a1bf8f-84df-49c1-82ac-8197a5b4b9a7",
                service_name: "Processos",
                description:
                  "Verifique todos os processos criados e altere suas informações.",
                display_icon: "shuffle",
                complete_route: "humanResources/management/processes",
                route: "processes",
                enabled: true,
                has_access: true,
                created_at: "2021-10-08T18:00:20.363Z",
              },
              {
                service_id: "5715e73e-4c0f-4ade-a8bf-1bc0dd98f213",
                service_name: "Colaboradores",
                description:
                  "Veja a lista completa dos colaboradores cadastrados, crie, edite e inative de acordo com a necessidade do seu negócio.",
                display_icon: "users",
                complete_route: "humanResources/management/employees",
                route: "employees",
                enabled: true,
                has_access: true,
                created_at: "2021-10-08T17:57:34.370Z",
              },
            ],
          },
          {
            submodule_id: "d627493e-6456-4b00-946b-afdd4b39b803",
            name: "Configurações",
            description: null,
            display_icon: "settings",
            complete_route: "humanResources/settings",
            route: "settings",
            enabled: true,
            has_access: true,
            created_at: "2021-10-08T17:50:21.660Z",
            services: [
              {
                service_id: "6a10ca2d-ae35-4f4e-9878-911c9125b31e",
                service_name: "Tipos de Anexo",
                description:
                  "Veja a lista completa dos tipos de anexos cadastrados, crie, edite, inative de acordo com a necessidade do seu negócio.",
                display_icon: "paperclip",
                complete_route: "humanResources/settings/attachment-types",
                route: "attachment-types",
                enabled: true,
                has_access: true,
                created_at: "2022-01-11T10:30:57.156Z",
              },
              {
                service_id: "1d4b6f9b-baef-474b-b6cf-f7171376343d",
                service_name: "Equipe de Atuação",
                description:
                  "Verifique e edite quais áreas de atuação estarão disponíveis dentro do sistema.",
                display_icon: "file-text",
                complete_route: "humanResources/settings/occupation-area",
                route: "occupation-area",
                enabled: true,
                has_access: true,
                created_at: "2021-10-08T18:05:54.870Z",
              },
            ],
          },
        ],
      },
      {
        module_id: "9c54e1ce-576a-47f9-9c6c-be6c388c236b",
        name: "4Tax - Colombia",
        description: ".",
        display_icon: "dollar-sign",
        route: "colombiaTax",
        has_access: true,
        created_at: "2021-11-03T13:46:03.351Z",
        submodules: [
          {
            submodule_id: "4671af02-3fbc-4abe-a5c9-5f550fcfe5dd",
            name: "Informes",
            description:
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac lacinia velit",
            display_icon: "trending-up",
            complete_route: "colombiaTax/colombiaReports",
            route: "colombiaReports",
            enabled: true,
            has_access: true,
            created_at: "2022-04-25T12:54:43.232Z",
            services: [
              {
                service_id: "85b23286-9e85-4ec3-8a23-7b9b0ceea2f0",
                service_name: "Perdidas y Ganancias",
                description:
                  "Información de los saldos de las cuentas de ingresos y gastos, según fecha seleccionada, con la información del contador, representante legal y/o revisor fiscal.",
                display_icon: "file-plus",
                complete_route: "colombiaTax/colombiaReports/profitAndLoss",
                route: "profitAndLoss",
                enabled: true,
                has_access: true,
                created_at: "2022-08-18T18:33:41.793Z",
              },
              {
                service_id: "29d532a0-6982-4132-b0ec-a5fa09a6cee0",
                service_name: "Retenciones",
                description:
                  "Información de la tabla de retenciones configuradas en la base de datos. Si se crea un codigo nuevo, este se integrará automaticamente",
                display_icon: "arrow-left",
                complete_route: "colombiaTax/colombiaReports/purchaseAndSale",
                route: "purchaseAndSale",
                enabled: true,
                has_access: true,
                created_at: "2022-08-18T17:52:01.103Z",
              },
              {
                service_id: "d00601e1-789c-499b-93ae-228680aa8294",
                service_name: "Diferidos en Compras y Ventas",
                description:
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                display_icon: "file-text",
                complete_route:
                  "colombiaTax/colombiaReports/deferredPurchaseAndSale",
                route: "deferredPurchaseAndSale",
                enabled: true,
                has_access: false,
                created_at: "2022-10-27T14:25:03.560Z",
              },
              {
                service_id: "542e3e1c-75e4-4463-abfc-cb0b2bf025f0",
                service_name: " IFRS - Inventario",
                description:
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                display_icon: "file-text",
                complete_route: "colombiaTax/colombiaReports/inventory",
                route: "inventory",
                enabled: true,
                has_access: false,
                created_at: "2022-10-27T14:27:34.552Z",
              },
              {
                service_id: "2a3cd1fa-4816-4651-b3ea-49b72f1a62b2",
                service_name: "IFRS - Cartera",
                description:
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                display_icon: "file-text",
                complete_route: "colombiaTax/colombiaReports/wallet",
                route: "wallet",
                enabled: true,
                has_access: false,
                created_at: "2022-10-27T14:28:47.838Z",
              },
              {
                service_id: "0ac9bb7a-e681-4436-800a-e34e3ece3e8c",
                service_name: "IFRS - Ingresos",
                description:
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                display_icon: "file-text",
                complete_route: "colombiaTax/colombiaReports/income",
                route: "income",
                enabled: true,
                has_access: false,
                created_at: "2022-10-27T14:29:52.130Z",
              },
              {
                service_id: "c5d39e20-8c50-439c-9ec0-1899b6a37319",
                service_name: "Balance de Prueba",
                description:
                  "Información de movimientos y saldos de las cuentas según las fechas seleccionadas",
                display_icon: "file-minus",
                complete_route: "colombiaTax/colombiaReports/thirdPartyBalance",
                route: "thirdPartyBalance",
                enabled: true,
                has_access: true,
                created_at: "2022-08-18T17:40:27.062Z",
              },
              {
                service_id: "50af04ff-e2a1-4a8b-a1bd-3c9235ded4ba",
                service_name: "Libros contables",
                description:
                  "Información de los libros oficiales: Libro mayor, libro de inventarios, libro diario por cuenta y por documento a nivel 4 y 5",
                display_icon: "book-open",
                complete_route: "colombiaTax/colombiaReports/accountingBooks",
                route: "accountingBooks",
                enabled: true,
                has_access: true,
                created_at: "2022-08-18T18:28:45.618Z",
              },
              {
                service_id: "287c877e-8b55-4e21-a35d-c82d47f7a7ba",
                service_name: "Informes de IVA",
                description:
                  "Información de los movimientos de IVA en el sistema para compras o ventas.",
                display_icon: "shopping-cart",
                complete_route: "colombiaTax/colombiaReports/ivaReports",
                route: "ivaReports",
                enabled: true,
                has_access: true,
                created_at: "2022-08-18T18:32:12.852Z",
              },
              {
                service_id: "e0fb5a3c-606f-4d9b-ba96-39642bfaff9d",
                service_name: "Legalizaciones",
                description:
                  "Información sobre los anticipos, caja menor que han sido causados, que aún no estan contabilizados o que fueron cancelados.",
                display_icon: "briefcase",
                complete_route: "colombiaTax/colombiaReports/legitimation",
                route: "legitimation",
                enabled: true,
                has_access: true,
                created_at: "2022-04-25T12:55:37.264Z",
              },
              {},
              {
                service_id: "75107e5b-aaaf-40ce-91a0-419d77c4ec15",
                service_name: "Certificado de Retención",
                description:
                  "Imprime el certificado por socio de negocio o de forma masiva según este sea solicitado.",
                display_icon: "file",
                complete_route:
                  "colombiaTax/colombiaReports/retentionCertificate",
                route: "retentionCertificate",
                enabled: true,
                has_access: true,
                created_at: "2022-08-18T17:54:40.661Z",
              },
              {
                service_id: "97ea4001-b8f5-46a5-838c-409a875d5241",
                service_name: "Balance General",
                description:
                  "Información de los saldos de las cuentas de activos, pasivos y patrimonio, según fecha seleccionada, con la información del contador, representante legal y/o revisor fiscal.",
                display_icon: "pie-chart",
                complete_route: "colombiaTax/colombiaReports/balanceSheet",
                route: "balanceSheet",
                enabled: true,
                has_access: true,
                created_at: "2022-08-18T18:30:39.959Z",
              },
            ],
          },
          {
            submodule_id: "f087d55d-a3b4-40ec-be8a-549e1ce436ff",
            name: "Impuestos",
            description: ".",
            display_icon: "percent",
            complete_route: "colombiaTax/colombiaTaxes",
            route: "colombiaTaxes",
            enabled: true,
            has_access: true,
            created_at: "2021-11-03T14:04:05.528Z",
            services: [
              {
                service_id: "e3506c3f-e72c-4f1d-af4d-f8c155defe24",
                service_name: "Retención de Impuestos",
                description: "Tabla con impuestos y retenciones para consulta",
                display_icon: "percent",
                complete_route:
                  "colombiaTax/colombiaTaxes/colombiaTaxes-withholding",
                route: "colombiaTaxes-withholding",
                enabled: true,
                has_access: true,
                created_at: "2021-11-03T14:19:13.385Z",
              },
            ],
          },
          {
            submodule_id: "de18114a-ad9c-4d0d-b021-877db427c4cb",
            name: "Contabilidad",
            description: ".",
            display_icon: "file-text",
            complete_route: "colombiaTax/colombiaContabilidad",
            route: "colombiaContabilidad",
            enabled: true,
            has_access: true,
            created_at: "2021-11-03T13:49:37.695Z",
            services: [
              {
                service_id: "b9a1d78e-fc73-4852-9a32-716792bed249",
                service_name: "Plan de Cuentas",
                description:
                  "La forma en que Contabilidad registra los hechos que afectan (o pueden afectar) el patrimonio de la empresa.",
                display_icon: "book-open",
                complete_route:
                  "colombiaTax/colombiaContabilidad/colombiaChartAccounts",
                route: "colombiaChartAccounts",
                enabled: true,
                has_access: true,
                created_at: "2021-11-03T14:12:10.509Z",
              },
              {
                service_id: "b11d47bf-5f80-46d0-86f5-e40e83f8cddb",
                service_name: "Perfiles Fiscales",
                description:
                  "Conjunto de propiedades generales o específicas del módulo.",
                display_icon: "users",
                complete_route:
                  "colombiaTax/colombiaContabilidad/colombiaTaxProfiles",
                route: "colombiaTaxProfiles",
                enabled: true,
                has_access: true,
                created_at: "2021-11-03T14:09:25.338Z",
              },
              {
                service_id: "1eb3d408-7c56-46d0-bf34-41e52f9749a4",
                service_name: "Cuentas Contables",
                description:
                  "Denominaciones técnicas utilizadas para representar elementos de la misma naturaleza, ya sean patrimoniales o resultantes.",
                display_icon: "grid",
                complete_route:
                  "colombiaTax/colombiaContabilidad/colombiaFinancialAccounts",
                route: "colombiaFinancialAccounts",
                enabled: true,
                has_access: true,
                created_at: "2021-11-03T14:11:15.827Z",
              },
              {
                service_id: "84a8dbbd-b973-4200-94e8-3ed220ff2782",
                service_name: "Transacciones Contables",
                description:
                  "Documentos que describen todos los datos contables y financieros de una organización en un período determinado.",
                display_icon: "shuffle",
                complete_route:
                  "colombiaTax/colombiaContabilidad/colombiaTransacciones-contables",
                route: "colombiaTransacciones-contables",
                enabled: true,
                has_access: true,
                created_at: "2021-11-03T14:14:36.356Z",
              },
              {
                service_id: "d04f46cd-fb26-4f43-8696-63520c1c387f",
                service_name: "Socio de Negocios",
                description: "Consulta los datos de tus socios de negocio.",
                display_icon: "briefcase",
                complete_route:
                  "colombiaTax/colombiaContabilidad/colombiaPartners",
                route: "colombiaPartners",
                enabled: true,
                has_access: true,
                created_at: "2022-08-22T17:04:35.809Z",
              },
              {
                service_id: "1163408d-814e-4794-aadc-21c952d214c7",
                service_name: "Documentos Contables",
                description:
                  "El conjunto de cuentas, previamente establecidas, que orientan la labor contable de registros, hechos y actos inherentes ...",
                display_icon: "file-text",
                complete_route:
                  "colombiaTax/colombiaContabilidad/colombiaAccountingDocument",
                route: "colombiaAccountingDocument",
                enabled: true,
                has_access: true,
                created_at: "2021-11-03T14:13:06.490Z",
              },
            ],
          },
        ],
      },
      {
        module_id: "98ed0863-afd6-4a74-8df7-8ee14d8a9eae",
        name: "Serviços",
        description: ".",
        display_icon: "box",
        route: "services",
        has_access: true,
        created_at: "2021-12-27T12:20:37.552Z",
        submodules: [
          {
            submodule_id: "27bda5de-b0ee-4f74-a2df-332c1f39434d",
            name: "Configurações de Serviços",
            description: null,
            display_icon: "settings",
            complete_route: "services/service-settings",
            route: "service-settings",
            enabled: true,
            has_access: true,
            created_at: "2021-12-27T12:39:50.492Z",
            services: [
              {
                service_id: "6a171868-136d-497c-91e1-27031e2afa50",
                service_name: "Tipos de Anexos",
                description:
                  "Veja a lista completa dos tipos de anexos cadastrados, crie, edite, inative de acordo com a necessidade do seu negócio.",
                display_icon: "paperclip",
                complete_route: "services/service-settings/attachments",
                route: "attachments",
                enabled: true,
                has_access: true,
                created_at: "2021-12-27T12:55:20.238Z",
              },
              {
                service_id: "8eae7ac8-4e44-4d7f-9999-9a692f39f0b1",
                service_name: "Unidade de Negócio e Portfólio de Serviços",
                description:
                  "Aqui você encontra a listagem das Associações e pode realizar a manutenção das Unidades de Negócio e o Portfólio de Serviços.",
                display_icon: "layers",
                complete_route:
                  "services/service-settings/portfolio-business-unit-association",
                route: "portfolio-business-unit-association",
                enabled: true,
                has_access: true,
                created_at: "2022-08-25T18:30:36.239Z",
              },
              {
                service_id: "a5cd17b8-e493-4a64-8e3d-6344785b7143",
                service_name: "Fechamento de Período",
                description:
                  "Veja todo os períodos para lançamento de hora disponíveis , crie novos, e faça a a abertura e fechamento deles.",
                display_icon: "unlock",
                complete_route: "services/service-settings/processing-period",
                route: "processing-period",
                enabled: true,
                has_access: false,
                created_at: "2022-10-28T18:29:42.462Z",
              },
            ],
          },
          {
            submodule_id: "7e285a2b-3198-4863-834c-a06969211dab",
            name: "Gestão de Horas",
            description: null,
            display_icon: "clock",
            complete_route: "services/time-management",
            route: "time-management",
            enabled: true,
            has_access: true,
            created_at: "2022-02-10T17:10:57.978Z",
            services: [
              {
                service_id: "b9017442-094a-465c-8912-5e11ab8ba147",
                service_name: "Lançamento de Horas",
                description:
                  "Realize a edição e lançamento das horas trabalhadas em cada contrato de serviço.",
                display_icon: "clock",
                complete_route: "services/time-management/launch-of-hours",
                route: "launch-of-hours",
                enabled: true,
                has_access: true,
                created_at: "2022-02-10T17:16:41.930Z",
              },
              {
                service_id: "ef506f5a-d968-43d2-badf-641397feaae7",
                service_name: "Aprovação de Horas",
                description:
                  "Aqui você realiza a aprovação/reprovação da horas lançadas.",
                display_icon: "user-check",
                complete_route: "services/time-management/time-sheet-approval",
                route: "time-sheet-approval",
                enabled: true,
                has_access: true,
                created_at: "2022-07-13T12:54:24.911Z",
              },
              {
                service_id: "1b3f0ba9-9b26-4c51-a3be-4c060b69c7fc",
                service_name: "Resumo Semanal",
                description:
                  "Aqui você encontra o resumo dos lançamentos semanais",
                display_icon: "rotate-ccw",
                complete_route: "services/time-management/weekly-summary",
                route: "weekly-summary",
                enabled: true,
                has_access: true,
                created_at: "2022-03-17T18:13:30.367Z",
              },
              {
                service_id: "dd783684-5952-4e87-ab8d-daf5ecf3b427",
                service_name: "Relatório de Horas Lançadas",
                description: "Consulte o relatório de Lançamento de Horas",
                display_icon: "clipboard",
                complete_route:
                  "services/time-management/report-launch-of-hours",
                route: "report-launch-of-hours",
                enabled: true,
                has_access: true,
                created_at: "2022-03-14T15:12:53.138Z",
              },
              {
                service_id: "54290054-b5dc-4ee7-84d0-7a6a2e4d2329",
                service_name: "Resumo Mensal",
                description:
                  "Aqui você encontra o resumo dos lançamentos mensais.",
                display_icon: "calendar",
                complete_route: "services/time-management/monthly-summary",
                route: "monthly-summary",
                enabled: true,
                has_access: true,
                created_at: "2022-03-17T18:09:49.236Z",
              },
              {},
            ],
          },
          {
            submodule_id: "361d05c7-2763-4a86-9861-323aec81dfd6",
            name: "Contratos",
            description: "",
            display_icon: "file-text",
            complete_route: "services/service-contracts",
            route: "service-contracts",
            enabled: true,
            has_access: true,
            created_at: "2021-12-27T12:46:12.313Z",
            services: [
              {
                service_id: "25d63a14-ed52-4f3c-a4e6-40cb9b75967a",
                service_name: "Contratos de Serviços",
                description:
                  "Veja a lista completa dos contratos cadastrados, crie, edite, inative de acordo com a necessidade do seu negócio.",
                display_icon: "file-text",
                complete_route: "services/service-contracts/contract-list",
                route: "contract-list",
                enabled: true,
                has_access: true,
                created_at: "2021-12-27T12:53:03.279Z",
              },
              {
                service_id: "741e30e2-fa58-498f-923b-a02dba66c2e1",
                service_name: "Associação de Colaboradores",
                description:
                  "Realize a associação de Colaboradores em seus devidos contratos de serviço.",
                display_icon: "user",
                complete_route: "services/service-contracts/staff-association",
                route: "staff-association",
                enabled: true,
                has_access: true,
                created_at: "2022-02-10T17:20:01.153Z",
              },
            ],
          },
        ],
      },
      {
        module_id: "1b1e8292-5ce5-4c15-98ce-f3d7556366e7",
        name: "Inbound",
        description: ".",
        display_icon: "file-text",
        route: "inbound",
        has_access: true,
        created_at: "2022-01-06T12:14:12.248Z",
        submodules: [
          {
            submodule_id: "10a79787-a8f5-4290-9960-2298de1f9996",
            name: "Configurações Inbound",
            description: "",
            display_icon: "settings",
            complete_route: "inbound/inboundSettings",
            route: "inboundSettings",
            enabled: true,
            has_access: true,
            created_at: "2022-01-06T13:46:37.828Z",
            services: [
              {
                service_id: "a506130a-594b-4455-89d1-9211ee6c9ede",
                service_name: "Configurações Gerais",
                description:
                  "Defina aqui as configurações para busca de documentos fiscais",
                display_icon: "settings",
                complete_route: "inbound/inboundSettings/generalSettings",
                route: "generalSettings",
                enabled: true,
                has_access: true,
                created_at: "2022-01-06T13:54:11.529Z",
              },
            ],
          },
          {
            submodule_id: "500ff8ae-dbcd-48ef-9db7-e0bcef6931da",
            name: "Monitores Inbound",
            description: null,
            display_icon: "monitor",
            complete_route: "inbound/inboundMonitors",
            route: "inboundMonitors",
            enabled: true,
            has_access: true,
            created_at: "2022-01-06T13:45:31.085Z",
            services: [
              {
                service_id: "d9338bd0-bae0-41bb-a6f5-2c7382abfcc6",
                service_name: "Monitor de Documentos",
                description:
                  "Lista de documentos importados do Ambiente Nacional e SEFAZ",
                display_icon: "monitor",
                complete_route: "inbound/inboundMonitors/documentsMonitor",
                route: "documentsMonitor",
                enabled: true,
                has_access: true,
                created_at: "2022-01-06T13:49:32.030Z",
              },
            ],
          },
        ],
      },
    ],
  },
  _persist: { version: 2, rehydrated: true },
};

export default mock;
